### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by denisefavila**
influx_db_client, rumqtt and sentry

fixing some openssl issues.

### CODE REVIEW

**Comment by otavio** [comment]
As far as understand this is a library so no `Cargo.lock` should be used. Instead, constraints for versions should be added on `Cargo.toml` so the apps can update their crates if compatible.

**Comment by denisefavila** [comment]
> As far as understand this is a library so no `Cargo.lock` should be used. Instead, constraints for versions should be added on `Cargo.toml` so the apps can update their crates if compatible.

I just kept the Cargo.lock file for consistency, given that the previous one already existed, even though it is not used.

**Comment by otavio** [comment]
If unused, maybe, it's better to remove it on a previous commit prior bumping the deps?

**Review by gabisurita — APPROVED** [review]
I'm +1 with removing the lockfile, but we can do it on a future PR.

**Review by akionakamura — APPROVED** [review]

**Pull request merged**
